apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-incremental-backup
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: pg-incremental-backup
            image: postgres:17-alpine
            env:
            - name: PGPASSWORD
              value: pgpass
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: stg-acc-secret
                  key: AZCOPY_ACCOUNT_NAME
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: stg-acc-secret
                  key: AZCOPY_ACCOUNT_KEY
            volumeMounts:
            - name: backup-data
              mountPath: /backup
            command:
            - /bin/bash
            - -c
            - |
              set -e

              # Install required packages
              apk add --no-cache curl tar bash postgresql-client

              # Install AzCopy
              curl -L https://aka.ms/downloadazcopy-v10-linux | tar -xz -C /tmp
              cp /tmp/azcopy_linux_amd64_*/azcopy /usr/bin/
              chmod +x /usr/bin/azcopy
              # Verify AzCopy installation
              azcopy --version

              echo "Starting PostgreSQL backup at $(date)"
              BACKUP_DIR="/backup"
              TIMESTAMP=$(date +%Y%m%d%H%M%S)
              BACKUP_FILE="$BACKUP_DIR/incremental-$TIMESTAMP.sql"

              # Perform the PostgreSQL backup
              pg_dump -h postgresql-ha-pgpool.default.svc.cluster.local -U postgres -F c -f "$BACKUP_FILE"

              echo "Uploading to Azure..."
              azcopy copy "$BACKUP_FILE" "https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/pgsql-backups/incremental-$TIMESTAMP.sql"

              echo "Backup completed at $(date)"

          volumes:
          - name: backup-data
            emptyDir: {}
