keycloak:
  replicaCount: 3
  fullnameOverride: postgresql-ha

  auth:
    adminUser: "admin"
    adminPassword: "kcpass"

  postgresql:
    enabled: false
  
  externalDatabase:
    host: postgres-postgresql-ha-pgpool.default.svc.cluster.local
    port: 5432
    user: "postgres"
    password: "pgpass"
    database: "postgres"
  
  extraVolumeMounts:
  - name: config
    mountPath: "/opt/bitnami/keycloak/data/import"
    readOnly: true
  
  extraVolumes:
    - name: config
      configMap:
        name: keycloak-realm
        items:
        - key: "realm.json"
          path: "realm.json"
  
  extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "--import-realm --verbose"