keycloak:
  proxy: edge
  extraEnvVars:
    - name: KC_PROXY
      value: "edge"
    - name: KC_CONFIG_BUILD
      value: "false"

  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 3
  
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 3
  
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi
