keycloak:
  replicaCount: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

  auth:
    adminUser: "admin"
    adminPassword: "kcpass"

  postgresql:
    enabled: false
  
  externalDatabase:
    host: postgres-postgresql-ha-pgpool.default.svc.cluster.local
    port: 5432
    user: "postgres"
    password: "pgpass"
    database: "postgres"
  
  extraVolumeMounts:
  - name: config
    mountPath: "/opt/bitnami/keycloak/data/import"
    readOnly: true
  
  extraVolumes:
    - name: config
      configMap:
        name: keycloak-realm
        items:
        - key: "iopreprod.json"
          path: "iopreprod.json"
  
  extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "--import-realm"