keycloak:
  proxy: edge
  extraEnvVars:
    - name: KC_PROXY
      value: "edge"
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60