keycloak:
  replicaCount: 3

  auth:
    adminPassword: "kcpass"

  postgresql:
    enabled: false
  
  externalDatabase:
    host: postgres-postgresql-ha-pgpool.default.svc.cluster.local
    port: 5432
    user: "postgres"
    password: "pgpass"
    database: "postgres"
  
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"
  
  extraVolumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
  extraVolumes:
    - name: config
      configMap:
        name: keycloak-realm
        items:
        - key: "realm.json"
          path: "realm.json"