namespaceOverride: vignaraj

persistence:
  size: 0.5Gi
  storageClass: my-storageclass

postgresql:
  replicaCount: 3
  username: postgres
  password: pgpass
  adminUsername: ckpadmin
  adminPassword: ckppass
  repmgrPassword: repmgrpass

pgpool:
  replicaCount: 2
  adminPassword: pgpooladminpass

  configuration: |
    failover_on_backend_error = "on"
