postgresql-ha:
  fullnameOverride: postgresql-ha
  persistence:
    size: 0.5Gi
    storageClass: my-storageclass

  postgresql:
    replicaCount: 3
    username: postgres
    password: pgpass
    adminUsername: ckpadmin
    adminPassword: ckppass
    repmgrPassword: repmgrpass
    livenessProbe:
      initialDelaySeconds: 60
    readinessProbe:
      initialDelaySeconds: 60

  pgpool:
    replicaCount: 2
    adminPassword: pgpooladminpass

    configuration: |
      failover_on_backend_error = "on"
      load_balance_mode = "on"
      statement_level_load_balance = "on"
  
  backup:
    enabled: true
    cronjob:
      schedule: "*/2 * * * *"
      command: 
        - /bin/sh
        - -c
        - |
          pg_basebackup -D /backup -x
  
  primary:
    extendedConfiguration: |
      archive_mode = on
      wal_level = replica
      archive_command = 'mkdir -p /bitnami/postgresql/wal-archive && test ! -f /bitnami/postgresql/wal-archive/%f && cp %p /bitnami/postgresql/wal-archive/%f'