postgresql-ha:
  fullnameOverride: postgresql-ha
  persistence:
    size: 0.5Gi
    storageClass: my-storageclass

  postgresql:
    replicaCount: 3
    username: postgres
    password: pgpass
    adminUsername: ckpadmin
    adminPassword: ckppass
    repmgrPassword: repmgrpass
    livenessProbe:
      initialDelaySeconds: 60
    readinessProbe:
      initialDelaySeconds: 60

  pgpool:
    replicaCount: 2
    adminPassword: pgpooladminpass

    configuration: |
      failover_on_backend_error = "on"
      load_balance_mode = "on"
      statement_level_load_balance = "on"
  
  backup:
    enabled: true
    cronjob:
      schedule: "*/2 * * * *"
      command: 
        - /bin/sh
        - -c
        - |
          set -e

          # Load secret values
          export AZCOPY_ACCOUNT_NAME=$(cat /mnt/secrets/AZCOPY_ACCOUNT_NAME)
          export AZCOPY_ACCOUNT_KEY=$(cat /mnt/secrets/AZCOPY_ACCOUNT_KEY)

          apt-get update && apt-get install -y wget unzip curl

          # Install azcopy
          wget -O azcopy.zip https://aka.ms/downloadazcopy-v10-linux
          unzip azcopy.zip -d azcopy
          cp ./azcopy/azcopy_linux_amd64_*/azcopy /usr/bin/
          chmod +x /usr/bin/azcopy

          # Dump PostgreSQL
          BACKUP_FILE="/backup/pgdump/pg_dumpall-$(date '+%Y-%m-%d-%H-%M').sql"
          pg_dumpall --clean --if-exists --quote-all-identifiers --no-password --file="$BACKUP_FILE"

          # Upload to Azure Blob Storage
          DEST_URL="https://${AZCOPY_ACCOUNT_NAME}.blob.core.windows.net/pgsql-backups"
          azcopy copy "$BACKUP_FILE" "$DEST_URL" \
            --from-to=LocalBlob \
            --recursive=false \
            --dest-account-name="$AZCOPY_ACCOUNT_NAME" \
            --dest-account-key="$AZCOPY_ACCOUNT_KEY"
      extraVolumes:
        - name: stg-acc-secret
          secret:
            secretName: stg-acc-secret

      extraVolumeMounts:
        - name: stg-acc-secret
          mountPath: /mnt/secrets
          readOnly: true