namespaceOverride: vignaraj

persistence:
  size: 0.5Gi
  storageClass: my-storageclass

postgresql:
  replicaCount: 1
  username: postgres
  password: pgpass
  adminUsername: ckpadmin
  adminPassword: ckppass
  repmgrPassword: repmgrpass
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60

pgpool:
  replicaCount: 3
  adminPassword: pgpooladminpass

  configuration: |
    failover_on_backend_error = "on"
