postgresql-ha: 
  persistence:
    size: 0.5Gi
    storageClass: my-storageclass
  
  postgresql:
    replicaCount: 3
    username: postgres
    password: pgpass
    adminUsername: ckpadmin
    adminPassword: ckppass
    repmgrPassword: repmgrpass
    livenessProbe:
      initialDelaySeconds: 60
    readinessProbe:
      initialDelaySeconds: 60
  
  pgpool:
    replicaCount: 2
  adminPassword: pgpooladminpass

  configuration: |
    failover_on_backend_error = "on"
    load_balance_mode = "on"
    statement_level_load_balance = "on"
