{{$root := . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
stringData:
  username: {{ $root.Values.postgres.username }}
  password: {{ $root.Values.postgres.password }}