apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: keycloak-realm-import
  namespace: keycloak
  labels:
    app: sso
spec:
  keycloakCRName: keycloak
  realm:
    {{ .Files.Get "files/realm.json" | indent 4 }}
