apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: example-keycloak-realm-import
  labels:
    app: sso
spec:
  keycloakCRName: example-keycloak
  realm:
    configMap:
      name: keycloak-realm
      key: realm.json
